Budget-app (ROR app)
Nessrine88/My-Budget-RoR-app pull request #3
Opened 2024-02-16 18:56 UTC by Nessrine88

In this milestone I have implemented the following requirements:
Splash screen

A simple page with the name of your app (yes, you need to choose one), and links to the sign up and log in pages.
Sign up and log in pages

The user should be able to register in the app with full name, email and password (all mandatory).
The user can log into the app using email and password.
If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).
Home page (categories page)

When the user logs in, they are presented with the categories page.
For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
There is a button "add a new category" at the bottom that brings the user to the page to create a new category.
Transactions page

For a given category, the list of transactions is presented, ordered by the most recent.
At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
When the user clicks on the "Back" button (<), the user navigates to the home page.
"Add a new category" page

The user fills out a form to create a new category, indicating their name and icon (both mandatory).
The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
When the user clicks on the "Back" button (<), the user navigates to the home page.
"Add a new transaction" page

The user fills out a form to create a new transaction with:
name (mandatory)
amount (mandatory)
categories (mandatory at least one)
The user click (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.
When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.
Testing requirements

Create unit and integration tests for all the most important components of your RoR application.

2024-02-16 21:02 UTC, shahadat3669 requested changes
Hi @Nessrine88, 

Great job so far! 👏 You've done well, and you're almost there for the next project ⏭️, but there are a few issues 🐛 that you still need to work on.

<img  src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif" />


## Don't Worry 🙏

It's okay to have bugs in your code. 🆗 Please see this code review as an opportunity to learn practical coding skills and discover new tips that can improve your code quality 💯 and help you **get even better** 💼.

**I will guide you on how to address these areas down below 👇.**

## Highlights
✅ No linter Errors
✅ Existing test cases passed


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadat3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-16 21:02 UTC, shahadat3669 commented on db/schema.rb
- [ ] Good job so far! However, there is a need to make changes to the schema. As per the project requirements, there is a many-to-many relationship between `groups` and `entities`. This implies that a group can contain multiple entities, and one entity can belong to multiple groups. To establish this type of relationship, you need to create an additional table and connect the two schema tables through that new table.
![image](https://github.com/Nessrine88/My-Budget-RoR-app/assets/55840999/c2523865-3939-4347-88fc-a50007254f23)

You've already encountered this type of relationship in the "Database" module. I recommend updating your code to reflect this many-to-many relationship. Additionally, after making these changes, thoroughly review and test your entire project to ensure everything works as expected. Keep up the good work! 🚀👍

2024-02-16 21:02 UTC, shahadat3669 commented on README.md
> +[E-Pocket](https://my-budget-ror-app.onrender.com/users/sign_up)
- [ ] Good job on the progress! However, during testing on the deployed version, I encountered an issue when attempting to create a new account. This is a critical functionality, and it's important to ensure a seamless user registration process. I recommend investigating and fixing the issue to ensure users can create accounts without encountering errors as I mentioned in the Zoom call. A smooth registration process is crucial for the overall user experience. Keep up the good work, and feel free to reach out if you have any questions or need assistance! 
- [ ] Additionally after updating all the changes please redeploy with the new update.🚀🛠️

2024-02-16 21:02 UTC, shahadat3669 commented on README.md
> + [Video-demo](https://www.loom.com/share/e67f9382573c4a8598f847a466b48427?sid=73011810-c223-4ec1-ba88-1d95342874b5)
- [ ] Great project presentation! However, to enhance it further, consider adding a segment where you highlight a piece of code that you find particularly interesting or are proud of. This can provide viewers with insights into your thought process, problem-solving skills, and coding style. Sharing a snippet of code you are passionate about can make your presentation more engaging and showcase your skills effectively. Keep up the good work, and feel free to reach out if you have any questions or need assistance! 🚀👩‍💻

2024-02-16 21:02 UTC, shahadat3669 commented on config/routes.rb
> +  root "groups#index"
- [ ] Great progress on your project! However, there is a missing component as per project requirements – the splash screen. The splash screen is an essential element, and its absence can impact the overall user experience. I recommend adding the splash screen following the design specifications. This will enhance the visual appeal of your application and align it with the project requirements. Keep up the good work! 🚀👍
![image](https://github.com/Nessrine88/My-Budget-RoR-app/assets/55840999/e7c844bd-8c7d-4f39-876b-ec41826babb7)

2024-02-16 21:02 UTC, shahadat3669 commented on app/views/devise/registrations/new.html.erb
- [ ] Great use of `devise` for user authentication! However, it seems there's an issue with creating a new account, resulting in an "Unpermitted parameters" error. To resolve this, ensure that your strong parameters in the controller permit all the necessary attributes for user creation. Double-check your `devise` configuration and make sure you're permitting the required parameters.

- [ ] Additionally, the signup page doesn't align with the design. Consider updating the styling to match the design specifications, providing a cohesive and visually appealing user experience.

| Your | Design |
| --- | --- |
|  ![image](https://github.com/Nessrine88/My-Budget-RoR-app/assets/55840999/561389f0-d2b7-40c1-81ab-a3d12fc66afe)| ![image](https://github.com/Nessrine88/My-Budget-RoR-app/assets/55840999/9846871b-9e48-4255-a4ae-1908893bb2b1)|

- [ ] Currently, you are not using the font that was specified in the design. I recommend that you update the font and follow the design. Please update the font family through out the project. 🙏 

Keep up the good work, and feel free to reach out if you have any questions or need further assistance! 🚀👩‍💻

2024-02-16 21:02 UTC, shahadat3669 commented on app/views/devise/sessions/new.html.erb
- [ ] Good job on adding the sign in page. but the signing page doesn't align with the design. Consider updating the styling to match the design specifications, providing a cohesive and visually appealing user experience.

| Your | Design |
| --- | --- |
|  ![image](https://github.com/Nessrine88/My-Budget-RoR-app/assets/55840999/22597328-391c-40c9-8d6d-c9304a1c1da9)| ![image](https://github.com/Nessrine88/My-Budget-RoR-app/assets/55840999/06f98102-dffa-4630-8012-8c0099f65692)|

2024-02-16 21:02 UTC, shahadat3669 commented on app/views/groups/new.html.erb
- [ ] Well done on the progress! However, there's a small improvement to consider. It's recommended to include a "Back" button (<) in the user interface. When users click on this button, it should navigate them back to the home page. This addition will enhance user navigation and provide a more seamless experience.
![image](https://github.com/Nessrine88/My-Budget-RoR-app/assets/55840999/78377a21-7672-4b17-a801-e4f203aba688)

Keep up the good work, and feel free to reach out if you have any questions or need further guidance! 🚀👩‍💻

2024-02-16 21:02 UTC, shahadat3669 commented on app/views/entities/index.html.erb
Certainly! Here's an improved version of your review:

- [x] Well done on the progress! However, there's a small improvement to consider. It's recommended to include a "Back" button (<) in the user interface. When users click on this button, it should navigate them back to the home page. This addition will enhance user navigation and provide a more seamless experience. You can implement it using a link or button with the appropriate routing.

![image](https://github.com/Nessrine88/My-Budget-RoR-app/assets/55840999/6318675a-1988-4a37-86e9-e9db928a733e)

- [ ] Additionally, as per project requirements, there should be a many-to-many relationship between `groups` and `entities`. Ensure that there is functionality to delete at least one category.
![image](https://github.com/Nessrine88/My-Budget-RoR-app/assets/55840999/d9dd0714-12a9-4614-8352-3f04c32e73f1)

Keep up the good work, and feel free to reach out if you have any questions or need further guidance! 🚀👩‍💻

2024-02-16 21:02 UTC, shahadat3669 commented on app/views/entities/index.html.erb
> +      <li class="table-bordered p-4" align="center"><strong>Total amount: <%=@total_amount%></strong> $</li>
- [ ] Great progress on your project! However, a minor adjustment is needed. The total amount should be displayed on the left side, and the corresponding amount should appear on the right side. This change will align with the expected design and improve the overall layout.

| Your | Design |
| --- | --- |
|  ![image](https://github.com/Nessrine88/My-Budget-RoR-app/assets/55840999/42158f16-35da-4aa6-a80c-015a842fba92)| ![image](https://github.com/Nessrine88/My-Budget-RoR-app/assets/55840999/2e28f2bf-0a11-4233-bb8f-69dd5a208cc4)|

Keep up the good work, and feel free to reach out if you have any questions or need further assistance! 🚀👩‍💻

2024-02-16 21:02 UTC, shahadat3669 commented on README.md
> +This project is [MIT](./LICENSE.md) licensed.
- [ ] Good work on your project! However, it seems that the license file is currently missing. To ensure compliance with open-source standards and make your project more accessible to others, please add a license file to your codebase. Adding a license file helps users understand how they can use, modify, and share your project. You can choose a license that aligns with your project's goals and legal requirements. Common licenses include MIT, Apache, or GPL.
![image](https://github.com/Nessrine88/My-Budget-RoR-app/assets/55840999/04353200-0584-4814-a2ad-7c82288c145e)

Keep up the good work, and let me know if you have any questions or need further assistance! 🚀📝

2024-02-16 21:02 UTC, shahadat3669 commented on config/routes.rb
> +    resources :entities
- [ ] Great work on your project! To further enhance your testing coverage, I recommend creating a Request spec file for all your controllers. This will help ensure comprehensive testing across your application.

Here's an example structure for creating a Request spec file:

```ruby
# spec/requests/users_request_spec.rb
require 'rails_helper'

RSpec.describe "Users", type: :request do
  # Your test cases for the Users controller can go here
  # For example:
  describe "GET /users" do
    it "returns a successful response" do
      get "/users"
      expect(response).to have_http_status(200)
    end
  end

  # Add similar blocks for other controller actions as needed
end
```

This will provide a dedicated space for testing HTTP requests and responses for your controllers.

Keep up the excellent work, and feel free to reach out if you have any questions or need further assistance! 🚀👩‍💻

2024-02-17 21:16 UTC, Davidosky007 requested changes
Hi @Nessrine88 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* All tests passed 👍 
* Well-written PR 👍 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidosky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-17 21:16 UTC, Davidosky007 commented on README.md
> -
* Kindly add your readme as it is missing, i guess you removed it by mistake, as a result, i can't check the previous CR's requested changes on your live demo link and video link

2024-02-17 21:16 UTC, Davidosky007 commented on config/routes.rb
> +    resources :entities
* Done 👌

2024-02-17 23:22 UTC, shahadat3669 requested changes
Hi @Nessrine88, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


<img src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Don't Worry 🙏

It's okay to have bugs in your code. 🆗 Please see this code review as an opportunity to learn practical coding skills and discover new tips that can improve your code quality 💯 and help you **get even better** 💼.

**I will guide you on how to address these areas down below 👇.**

## Highlights
✅ Video presentation updated
✅ Updated the readme file


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table  width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadat3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-17 23:22 UTC, shahadat3669 commented on README.md
> +[E-Pocket](https://my-budget-ror-app.onrender.com/users/sign_up)
- [ ] Good job so far, but there are still some changes needed. First of all, I noticed that you did not redeploy the updated code. I recommend redeploying with the latest commit. Additionally, in the existing deployed version, after signing in, when I try to create a category, it gives an error. As it is an internal server error, I failed to verify why it is happening. I recommend checking your deployed version and ensuring that you fix those issues.

https://github.com/Nessrine88/My-Budget-RoR-app/assets/55840999/0028c12f-b8a9-4374-a30a-58c598174ee6

- [ ] Please update your deployed link. 👍 
```suggestion

[E-Pocket](https://my-budget-ror-app.onrender.com)
```

2024-02-17 23:22 UTC, shahadat3669 commented on README.md
> +This project is [MIT](./LICENSE.md) licensed.
- [ ] Good work on your project! However, it seems that the license file is currently missing. To ensure compliance with open-source standards and make your project more accessible to others, please add a license file to your codebase. Adding a license file helps users understand how they can use, modify, and share your project. You can choose a license that aligns with your project's goals and legal requirements. Common licenses include MIT, Apache, or GPL.
![image](https://github.com/Nessrine88/My-Budget-RoR-app/assets/55840999/04353200-0584-4814-a2ad-7c82288c145e)

Keep up the good work, and let me know if you have any questions or need further assistance! 🚀📝

2024-02-18 01:38 UTC, Reem-lab approved these changes
# Hi @Nessrine88,  👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3GBG7xejOXhH7MyQkn/giphy.gif"/>

## Highlights

- [ ]  Descriptive PR⭐
- [ ]  No Linters error 🤩
- [ ] Good job working on controllers methods💪🏻
- [ ] Good job working on models and validations 🙏🏻
- [ ] Great job working on the views🔥🔥
- [ ] Great design ⭐
- [ ] Huge efforts on the tests 🔥🔥
- [ ] Kudos on for working on the deployment ✅
- [ ] Great fir presenting the video 💪🏻
- [ ] Professional README 🚀
- [ ] Authentication Setup with devise well 🔥
- [ ] Good job working on the requested changes ⭐🙏🏻



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-18 01:41 UTC, merged